export const CHANGE_ACTIVE_CATEGORY = 'globalState/CHANGE_ACTIVE_CATEGORY';
export const IS_LEFT_MENU_BUTTON_ACTIVE = 'globalState/IS_LEFT_MENU_BUTTON_ACTIVE';
export const CACHE_CATEGORY_LIST = 'globalState/CACHE_CATEGORY_LIST';
